#!/usr/bin/env bash

SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"

leftwm-command "UnloadTheme"

killall picom
killall dunst
killall redshift
killall polybar

while pgrep -u $UID -x polybar >/dev/null; do sleep 1; done

