#!/usr/bin/env bash
export SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"


#down the last running theme
if [ -f "/tmp/leftwm-theme-down" ]; then
    /tmp/leftwm-theme-down
rm /tmp/leftwm-theme-down
fi
ln -s $SCRIPTPATH/down /tmp/leftwm-theme-down

# disable caps lock
setxkbmap -option ctrl:nocaps &

# picom --experimental-backends &
dunst &
redshift -l 60.205238:24.654079 &
nitrogen --restore &

polybar -q main -c $SCRIPTPATH/config.ini &

# set the theme.ron config
leftwm-command "LoadTheme $SCRIPTPATH/theme.ron"

