name: Deploy Flake

on:
  push:
    branches:
      - "main"
  workflow_dispatch:

jobs:
  deploy:
    needs: [check-flake]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    strategy:
      matrix:
        machine:
          - "thor"

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Tailscale
      uses: tailscale/github-action@main
      with:
        oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
        oauth-secret: ${{ secrets.TS_OAUTH_CLIENT_SECRET }}
        tags: tag:ci

    - name: Install Nix
      uses: DeterminateSystems/nix-installer-action@main

    - name: Add machine(s) to known hosts
      id: ssh-known-hosts
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan ${{ matrix.machine }} >> ~/.ssh/known_hosts

    - name: Build and deploy
      run: |
        set -euxo pipefail
        nix run github:serokell/deploy-rs --skip-checks --hostname=${{ matrix.machine }}
